import React from 'react'
import { GRADE_COLORS } from '../utils/mockGrading.js'

function DownloadIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path d="M12 3v12M7 10l5 5 5-5M5 21h14" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
    </svg>
  )
}

function generateHealthCardPdf(result) {
  if (!window.jspdf?.jsPDF) {
    alert('PDF library is loading. Please try again in a moment.')
    return
  }

  const { jsPDF } = window.jspdf
  const doc = new jsPDF()
  const gradeColor = GRADE_COLORS[result.grade] || '#0f1111'

  doc.setFontSize(18)
  doc.setTextColor(255, 153, 0)
  doc.text('SecondLife Health Card', 20, 20)

  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text('Amazon Seller Tools · Tamper-proof grading record', 20, 28)

  doc.setDrawColor(221, 221, 221)
  doc.line(20, 32, 190, 32)

  const rows = [
    ['Item Name', result.itemName],
    ['Grade', result.grade],
    ['Defect Types', result.defects.length ? result.defects.join(', ') : 'None'],
    ['Confidence', `${result.confidence}%`],
    ['Graded By', result.gradedBy],
    ['Timestamp', result.timestamp],
    ['Seller ID', result.sellerId],
    ['Recommended Action', result.recommendedAction],
    ['Estimated Resale Value', `₹${result.estimatedResaleValue.toLocaleString('en-IN')}`],
    ['Original Price', `₹${result.originalPrice.toLocaleString('en-IN')}`],
    ['ASIN', result.asin],
    ['Category', result.category],
  ]

  let y = 42
  rows.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      doc.setFillColor(240, 242, 242)
      doc.rect(20, y - 5, 170, 10, 'F')
    }
    doc.setTextColor(86, 89, 89)
    doc.setFont(undefined, 'normal')
    doc.text(label, 22, y)
    if (label === 'Grade') {
      const hex = gradeColor.replace('#', '')
      doc.setTextColor(
        parseInt(hex.slice(0, 2), 16),
        parseInt(hex.slice(2, 4), 16),
        parseInt(hex.slice(4, 6), 16)
      )
    } else {
      doc.setTextColor(15, 17, 17)
    }
    doc.text(String(value), 80, y)
    y += 12
  })

  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by SecondLife AI Grader · Amazon Internal Use', 20, 280)

  const safeName = result.itemName.replace(/[^a-z0-9]/gi, '_').slice(0, 30)
  doc.save(`SecondLife_HealthCard_${safeName}.pdf`)
}

export default function HealthCard({ result }) {
  if (!result) return null

  const rows = [
    ['Item Name', result.itemName],
    ['Grade', result.grade],
    ['Defect Types', result.defects.length ? result.defects.join(', ') : 'None'],
    ['Confidence', `${result.confidence}%`],
    ['Graded By', result.gradedBy],
    ['Timestamp', result.timestamp],
    ['Seller ID', result.sellerId],
    ['Recommended Action', result.recommendedAction],
  ]

  return (
    <div className="mt-5 pt-4 border-t border-[#DDD]">
      <h3 className="text-sm font-bold text-[#0f1111] mb-3">Health Card</h3>
      <div className="border border-[#DDD]" style={{ borderRadius: '4px', overflow: 'hidden' }}>
        <table className="w-full text-xs">
          <tbody>
            {rows.map(([label, value], i) => (
              <tr
                key={label}
                style={{ backgroundColor: i % 2 === 0 ? '#F0F2F2' : '#FFFFFF' }}
              >
                <td className="px-3 py-2 text-[#565959] w-[40%] border-r border-[#DDD]">{label}</td>
                <td
                  className="px-3 py-2 text-[#0f1111]"
                  style={
                    label === 'Grade'
                      ? { color: GRADE_COLORS[result.grade], fontWeight: 700 }
                      : {}
                  }
                >
                  {value}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <button
        type="button"
        onClick={() => generateHealthCardPdf(result)}
        className="mt-3 flex items-center gap-1.5 text-sm hover:text-[#c7511f] hover:underline cursor-pointer bg-transparent border-none p-0"
        style={{ color: '#007185' }}
      >
        <DownloadIcon />
        Download Health Card (PDF)
      </button>
    </div>
  )
}
